# Generated by Django 5.2.9 on 2025-12-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('in_restaurant', 'Готовится в ресторане'), ('in_delivery', 'У курьера'), ('processed', 'Обработанный')], db_index=True, default='unprocessed', max_length=13, verbose_name='Статус'),
        ),
    ]
