# Generated by Django 5.2.9 on 2025-12-11 16:25

import django.core.validators
from django.db import migrations, models


def set_prices(apps, schema_editor):
    OrderItem = apps.get_model("foodcartapp", "OrderItem")
    for order_item in OrderItem.objects.select_related("product").iterator():
        order_item.price = order_item.product.price * order_item.quantity
        order_item.save(update_fields=["price"])


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0038_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Цена",
                null=True,
            ),
        ),
        migrations.RunPython(set_prices, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Цена",
            ),
        ),
    ]
